### PR TITLE
Adding guestbook-datomic PR

### PR DESCRIPTION
**Pull request by Folcon**
PR associated with #5.

### CODE REVIEW

**Comment by Folcon** [comment]
Not sure if you wanted to make changes to it =)...

**Comment by yogthos** [comment]
Looks good, I'll take a look at adding a note in the docs as well. Might be an idea to add a datomic section [here](https://github.com/luminus-framework/luminus/tree/master/resources/md). The sections displayed on the site are managed via config [here](https://github.com/luminus-framework/luminus/blob/master/resources/docpages.edn).

**Comment by Folcon** [comment]
Hmm, what types of things would you want me to document? A high level idea is sufficient, I can start to organise something and see what I come up with =)...

**Comment by yogthos** [comment]
I was thinking it might be good to give a brief overview of getting up and running with Datomic. Something similar to the existing material in the "Database Access" section, and we could link the sample project from there. If you can think of any gotchas to mention, stuff like using mem db for dev, etc. would be good to add.

**Comment by Folcon** [comment]
Ok, so sections on:
1) on development with datomic
2) datomic in production?
3) I'm working on getting [drawbridge](https://github.com/nrepl/drawbridge) working with heroku, something about this?

For `2.`, I'm not sure how worthwhile it is documenting (I really seem to have gone off the beaten path with my approach, but if you keep banging your head against the wall, sooner or later it gives 
😄...), but in my case datomic in production runs in heroku. The transactor has no access to the outside world (which I think makes it reasonably secure), as it doesn't bind to the external port and I bundle my jar file alongside the transactor so it can talk to it. The data is stored on heroku postgres store (which took some time to wrangle).

I'm not sure it's super robust, but for anyone wanting to run a datomic instance in the heroku ecosystem at a reasonable starting price point I've found it works great. I'm pretty sure that I can then work out how to migrate up if I need it, but for the moment, its sufficient. Do you want me to do a section on it?

**Comment by yogthos** [comment]
Yeah these sections sound pretty reasonable to help people get started. I'd focus on documenting things specific to using Datomic from Luminus, and link to the official docs for more details on Datomic itself. Giving an example of the Heroku setup would be great as well. I agree that it's generally a good idea not to expose the DB to the outside world. :)

**Comment by Folcon** [comment]
@yogthos I've got something drafted for 2), shall I pop it up somewhere? Maybe a PR on [the docs](https://github.com/luminus-framework/luminus)?.

For 1) I'm still working out what to write regarding it, and for 3) I've got something working, but there's still an [open issue I'm trying to get sorted out](https://github.com/nrepl/drawbridge/issues/25). I can document what I have working already, or hopefully I'll hear something soon and can get it fixed.

**Comment by yogthos** [comment]
Yeah, a PR for the docs site would be ideal, and probably wouldn't hurt to add what you've got already. Can always do another PR later once the issue resolves.

**Comment by Folcon** [comment]
[Here's the first draft](https://github.com/luminus-framework/luminus/pull/215).

**Comment by yogthos** [comment]
:+1:

**Pull request merged**
